# Generated by Django 5.1.1 on 2024-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppTwo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
