# Generated by Django 4.2.16 on 2024-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppTwo", "0002_member_age_member_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
